### ISSUE TITLE
allow to specify name and provided capability separately

### ISSUE THREAD

**Issue by richlv** [larsks/fakeprovide#12]
sometimes the dependency is on a path like /usr/bin/python3 . fakeprovide fails :

{code}
> ./fakeprovide /usr/bin/python3
Building binary RPM.
./fakeprovide: ERROR: Failed to build binary RPM.
error: line 1: Illegal char '/' in: Name:               fakeprovide-/usr/bin/python3
{code}

it would be great to provide name and what is provided separately. hacking the script and testing such an approach, it does work and yum/rpm sees it as a valid dependency

**Comment by larsks** [comment]
That's what the `-P` flag is for:

    fakeprovide -P /usr/bin/python3 fake-python3

**Comment by richlv** [comment]
ahh, thanks - wasn't obvious to me :)
i guess this also adds a provide "fake-python3", which isn't really needed - but doesn't do any harm either.
