### ISSUE TITLE
does this still work on fc27?

### ISSUE THREAD

**Issue by kn00tcn** [larsks/fakeprovide#14]
not sure if the OS changed or if i did something wrong or if the instructions are too vague

- made a dir, placed the script & makefile in it, installed

- `fakeprovide distropackagename`, it spits out `fakeprovide-distropackagename-201807101234-1.fc27.rpm`, dnf install it

- nothing changes, trying to install another package with some deps i dont want, it tries to install distropackagename as if the fakeprovide one isnt doing anything

EDIT: when i alter the script to not prefix the name, dnf says it will downgrade the package during the dependency scenario.... so is rpmfusion doing something different to their packages that lets them take over? (at least i thought it was, maybe it's doing something different, the packages i can think of were freetype-freeworld, audacity-freeworld, chromium-freeworld)

EDIT2: now i dont know what to think... trying two test cases: `dnf install mixxx --exclude upower` & `dnf install vlc --exclude samba*`, only vlc halts while mixxx acts like it never needed upower in the first place... even the spec file mentions upower-devel only for building so why does dnf think it needs upower!?

also getting errors when trying to write in the arch option while version works fine, plus it was unexpected to need to write the options before the package name

the readme should mention `make` & `rpm-build` are required

**Comment by larsks** [comment]
Hi there. Could you at some details to this bug report?

- What are you trying to install?
- What dependency specifically were you trying to provide? 
- After installing the fakeprovide generated package, does `rpm -q --whatprovides thethingyouaretryingtoprovide` return the fakeprovide generated package?

I'd like to try to reproduce this on my local system.

> even the spec file mentions upower-devel only for building so why does dnf think it needs upower!?

The spec file isn't the only source of dependency information.  RPM generates automatic dependencies for shared libraries, so typically if something requires a `-devel` package for building it will then automatically require the corresponding non-devel package at installation time.

**Comment by kn00tcn** [comment]
```
# fakeprovide upower
# dnf install fakeprovide-upower
```
```
# dnf provides upower

fakeprovide-upower-20180710075558-1.fc27.noarch : Fake provide for upower.
Repo        : @System
Matched from:
Provide    : upower

upower-0.99.7-1.fc27.i686 : Power Management Service
Repo        : updates
Matched from:
Provide    : upower = 0.99.7-1.fc27

(along with the rest of the arches/base repo versions)
```
```
# rpm -q --whatprovides upower
fakeprovide-upower-20180710075558-1.fc27.noarch
```
```
# dnf install mixxx
Installing:
 mixxx     x86_64    2.1.1-2.fc27    rpmfusion-free-updates
Installing dependencies:
 upower    x86_64    0.99.7-1.fc27    updates

(along with the other usual deps)
```

the thing is, `dnf install mixxx -exclude upower` doesnt block the installation, so maybe a better test case is trying to install `vlc` while fake providing anything `samba`

```
# fakeprovide samba-client-libs
# fakeprovide samba-common
# fakeprovide samba-common-libs
```
...then `dnf install vlc` ended up with an unexpected result, it's no longer asking to install the `samba-common` dep! yet it still asks for the other two, so here's the one time it actually worked

another test case is the brave browser, trying to fakeprovide `redhat-lsb`, it ignores it & continues trying to install 134 packages

**Comment by kn00tcn** [comment]
is it normal not to be able to see any of the fakeprovide packages when using `dnf list *provide*`?

**Comment by larsks** [comment]
Your problem around `upower` is that `mixxx` doesn't require `upower`, it requires:

    # yum repoquery --requires mixxx | grep -i power
    libupower-glib.so.3()(64bit)

So in order to satisfy that requirement, you would need to run:

    # ./fakeprovide -P 'libupower-glib.so.3()(64bit)' upower

After which:

    # rpm -qp --provides fakeprovide-upower-20180710123824-1.fc27.noarch.rpm
    fakeprovide-upower = 20180710123824-1.fc27
    libupower-glib.so.3()(64bit)
    upower

If we install this package and then run `yum install mixxx`, you will
see that `upower` is no longer in the list of packages to be
installed, because the requirement is already satisfied.

**Comment by larsks** [comment]
Running `dnf list '*provide*'` shows `fakeprovide-` generated packages when I run it.  Make sure to quote or escape those `*` characters, through, because otherwise they will match files in your current directory.

**Comment by kn00tcn** [comment]
alright... definitely getting somewhere

so basically, i should always use `--requires` to get a more specific list & if it's not a package name there, then i should use the `-P` switch (maybe? i dont know what a .so is)

the second test i got working was brave browser, it was requiring `lsb` rather than `redhat-lsb`, so the fake lsb was a success in this case

i still cant figure out vlc's samba, there's nothing `samba` listed, or even `smb`, some other package must be pulling it that i dont know how to find, normally i browse arch's site like https://www.archlinux.org/packages/extra/x86_64/vlc/ to visualize the dependency tree (by the way, arch has samba as optional, this is stupid how different distros make certain deps optional while other distros make them required)

**Comment by kn00tcn** [comment]
for some reason mixxx in f28 was triggering php to install!

i couldnt actually see any reference to php through any of the queries, including rpmfusion's src rpm... the only way was to --exclude during install & look at the error, nothing provided `/usr/bin/php`

so i tried `fakeprovide -P '/usr/bin/php'`, seems to work

this is seriously making me question hundreds of other packages, if their deps are just some generic guessing algorithm

**Comment by larsks** [comment]
> for some reason mixxx in f28 was triggering php to install!

The package explicitly includes `/usr/bin/php`:

```
# yum repoquery --requires mixxx | grep php
/usr/bin/php
```
