### ISSUE TITLE
Requires: /usr/bin/psql

### ISSUE THREAD

**Issue by laapsaap** [larsks/fakeprovide#8]
How about "Requires: /usr/bin/psql" ?

```
$ sh fakeprovide /usr/bin/pgsql
Building binary RPM.
fakeprovide: ERROR: Failed to build binary RPM.
error: line 1: Illegal char '/' in: Name:               fakeprovide-/usr/bin/pgsql
```

**Comment by laapsaap** [comment]
I fixed it manually in the spec file, but its a minor problem. The name in the spec file just dont wants '/' in it.

**Comment by larsks** [comment]
I think the easiest solution would be:

    fakeprovide -P /usr/bin/pgsql fakepgsql

This will generate:

  fakeprovide-fakepgsql-20160108110508-1.fc23.noarch.rpm

Which has:

    $ rpm -qp --provides fakeprovide-fakepgsql-20160108110508-1.fc23.noarch.rpm
    /usr/bin/pgsql
    fakepgsql
    fakeprovide-fakepgsql = 20160108110508-1.fc23
